import { Figtree } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import MoodToggling from "@/providers/MoodToggling";
import { SessionProvider } from "next-auth/react";

const figtree = Figtree({
  subsets: ["latin"],
});

export const metadata = {
  title: "MY BLOGS",
  description: "Generated by MOHAMED ASHRAF AS A BLOG POST WEBSITE",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${figtree.style}`}>
        <SessionProvider>
          <MoodToggling>
            {" "}
            <div className="container">
              <div className="wrapper">
                <Navbar />
                {children}
                <Footer />
              </div>
            </div>
          </MoodToggling>
        </SessionProvider>
      </body>
    </html>
  );
}
